Repository athulreji/twitter-assist, pull requests merged in 2022-10, with the labels that each got.

#2 Update README.md
  README.md
Labels: hacktober-accepted

#3 Update views.py
  mainapp/views.py
Labels: hacktober-accepted, hacktoberfest-accepted

#4 Update manage.py
  manage.py
Labels: hacktober-accepted, hacktoberfest-accepted

#5 Update dashboard.html
  mainapp/templates/dashboard.html
Labels: hacktoberfest-accepted

#6 Update settings.py
  twitter_assist/settings.py
Labels: hacktoberfest-accepted

#7 Update manage.py
  manage.py
Labels: hacktoberfest-accepted
